version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - "BOT_TOKEN=${BOT_TOKEN}"
      - "LOG_LEVEL=${LOG_LEVEL}"
      - "DB_URL=${DB_URL}"


    ports:
      - "${TG_PORT}:${TG_PORT}"

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: polldb
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrator:
      build:
        context: .
        dockerfile: migrator.Dockerfile
      restart: on-failure
      environment:
        - "BOT_TOKEN=${BOT_TOKEN}"
        - "LOG_LEVEL=${LOG_LEVEL}"
        - "ALEMBIC_URL=${ALEMBIC_URL}"
        - "DB_HOST=${DB_HOST}"

        - "DB_URL=${DB_URL}"

volumes:
  db_data:
