"""init_migration

Revision ID: 588a63aaf2ff
Revises: 
Create Date: 2025-01-31 20:39:54.946318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588a63aaf2ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('peer_id', sa.Integer(), index=True, unique=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), unique=True, index=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.func.now(), nullable=False)
    )

    op.create_table('polls',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('peer_id', sa.Integer(), sa.ForeignKey('users.peer_id'), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.func.now(), nullable=False),
        sa.Column('is_single_use', sa.Boolean(), server_default=sa.false())
    )

    op.create_table('questions',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('poll_id', sa.Integer(), sa.ForeignKey('polls.id'), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('with_options', sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column('with_multipy_options', sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.func.now(), nullable=False)
    )

    op.create_table('replies',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('question_id', sa.Integer(), index=True, nullable=False),
        sa.Column('peer_id', sa.Integer(), index=True, nullable=False),
        sa.Column('reply', sa.String(), server_default='')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_table('questions')
    op.drop_table('polls')
    op.drop_table('users')
    # ### end Alembic commands ###