"""add AnswerOption and UserResponse

Revision ID: 8c0cbb47bbf9
Revises: 983efc77bf0b
Create Date: 2025-07-07 17:48:16.404942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0cbb47bbf9'
down_revision: Union[str, None] = '983efc77bf0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anser_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anser_options_question_id'), 'anser_options', ['question_id'], unique=False)
    op.create_table('user_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('reply_text', sa.String(), nullable=True),
    sa.Column('peer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['peer_id'], ['users.peer_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_responses_id'), 'user_responses', ['id'], unique=False)
    op.create_index(op.f('ix_user_responses_question_id'), 'user_responses', ['question_id'], unique=False)
    op.drop_index('ix_replies_id', table_name='replies')
    op.drop_index('ix_replies_peer_id', table_name='replies')
    op.drop_index('ix_replies_question_id', table_name='replies')
    op.drop_table('replies')
    op.create_foreign_key(None, 'polls', 'questions', ['first_question_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'questions', ['next_question_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'questions', ['prev_question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'polls', type_='foreignkey')
    op.create_table('replies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('peer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reply', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='replies_pkey')
    )
    op.create_index('ix_replies_question_id', 'replies', ['question_id'], unique=False)
    op.create_index('ix_replies_peer_id', 'replies', ['peer_id'], unique=False)
    op.create_index('ix_replies_id', 'replies', ['id'], unique=False)
    op.drop_index(op.f('ix_user_responses_question_id'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_id'), table_name='user_responses')
    op.drop_table('user_responses')
    op.drop_index(op.f('ix_anser_options_question_id'), table_name='anser_options')
    op.drop_table('anser_options')
    # ### end Alembic commands ###
