"""implemented linked list in questions

Revision ID: 983efc77bf0b
Revises: 55318dbdc361
Create Date: 2025-04-07 20:22:13.487805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983efc77bf0b'
down_revision: Union[str, None] = '55318dbdc361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('first_question_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('next_question_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('prev_question_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'prev_question_id')
    op.drop_column('questions', 'next_question_id')
    op.drop_column('polls', 'first_question_id')
    # ### end Alembic commands ###